---
deployment:
  tasks: -export DEPLOYPATH=/home/user/public_html/
    -/bin/cp hivindex.html $DEPLOYPATH
    -/bin/cp spanishhivindex.html $DEPLOYPATH
    -/bin/cp Aboutme.html $DEPLOYPATH
    -/bin/cp aboutme.less $DEPLOYPATH
    -/bin/cp sobremi.html $DEPLOYPATH
    -/bin/cp whatishiv.html $DEPLOYPATH
    -/bin/cp whatishiv.less $DEPLOYPATH
    -/bin/cp
